### ISSUE TITLE
Data compression

### ISSUE THREAD

**Issue by krmax44** [k-nut/unisport#7]
By default, Caddy doesn't compress response data (quite odd). The `/courses` route currently serves ~2MB of JSON, so it would be nice to have compression. See the [Caddy docs](https://caddyserver.com/docs/caddyfile/directives/encode) for details. Thanks!

**Comment by k-nut** [comment]
I'm surprised I never noticed. Compression is now enabled bringing the unfiltered courses down to ~1/4 of the size.
